import { ICourse } from "@/services/course-scraper/types";

export const mockCourses: any[] = [
    {
        id: 272388,
        term: "202509",
        termDesc: "First Term: Sep - Dec 2025",
        courseReferenceNumber: "10393",
        partOfTerm: "1",
        courseNumber: "360",
        subject: "BIOL",
        subjectDescription: "Biology",
        sequenceNumber: "A01",
        campusDescription: "Main (Gordon Head)",
        scheduleTypeDescription: "Lecture",
        courseTitle: "Cell Biology",
        creditHours: 1.5,
        maximumEnrollment: 150,
        enrollment: 100,
        seatsAvailable: 50,
        waitCapacity: 100,
        waitCount: 0,
        waitAvailable: 100,
        crossList: null,
        crossListCapacity: null,
        crossListCount: null,
        crossListAvailable: null,
        creditHourHigh: null,
        creditHourLow: 1.5,
        creditHourIndicator: null,
        openSection: true,
        linkIdentifier: null,
        isSectionLinked: false,
        subjectCourse: "BIOL360",
        faculty: [
            {
                bannerId: "123456",
                category: "01",
                class: "net.hedtech.banner.student.faculty.FacultyDecorator",
                courseReferenceNumber: "10393",
                displayName: "Dr. Sarah Johnson",
                emailAddress: "sjohnson@uvic.ca",
                primaryIndicator: true,
                term: "202509",
            },
        ],
        meetingsFaculty: [
            {
                category: "01",
                class: "net.hedtech.banner.student.schedule.SectionSessionDecorator",
                courseReferenceNumber: "10393",
                faculty: [],
                meetingTime: {
                    beginTime: "1300",
                    building: "161",
                    buildingDescription: "Science Building",
                    campus: "M",
                    campusDescription: "Main (Gordon Head)",
                    category: "01",
                    class: "net.hedtech.banner.general.overall.MeetingTimeDecorator",
                    courseReferenceNumber: "10393",
                    creditHourSession: 1.5,
                    endDate: "Dec 03, 2025",
                    endTime: "1350", // 50 minute class
                    friday: false,
                    hoursWeek: 3,
                    meetingScheduleType: "LEC",
                    meetingType: "CLAS",
                    meetingTypeDescription: "Every Week",
                    monday: true,
                    room: "A101",
                    saturday: false,
                    startDate: "Sep 03, 2025",
                    sunday: false,
                    term: "202509",
                    thursday: true,
                    tuesday: false,
                    wednesday: true,
                },
                term: "202509",
            },
        ],
        reservedSeatSummary: null,
        sectionAttributes: null,
        instructionalMethod: "F2F",
        instructionalMethodDescription: "Face to Face Instruction",
    },
    {
        id: 272659,
        term: "202509",
        termDesc: "First Term: Sep - Dec 2025",
        courseReferenceNumber: "10758",
        partOfTerm: "1",
        courseNumber: "115",

        subject: "CSC",
        subjectDescription: "Computer Science",
        sequenceNumber: "A01",
        campusDescription: "Main (Gordon Head)",
        scheduleTypeDescription: "Lecture",
        courseTitle: "Fundamentals of Programming II",
        creditHours: 1.5,
        maximumEnrollment: 120,
        enrollment: 95,
        seatsAvailable: 25,
        waitCapacity: 50,
        waitCount: 5,
        waitAvailable: 45,
        crossList: null,
        crossListCapacity: null,
        crossListCount: null,
        crossListAvailable: null,
        creditHourHigh: null,
        creditHourLow: 1.5,
        creditHourIndicator: null,
        openSection: true,
        linkIdentifier: "B1",
        isSectionLinked: true,
        subjectCourse: "CSC115",
        faculty: [
            {
                bannerId: "789012",
                category: "01",
                class: "net.hedtech.banner.student.faculty.FacultyDecorator",
                courseReferenceNumber: "10758",
                displayName: "Prof. Michael Chen",
                emailAddress: "mchen@uvic.ca",
                primaryIndicator: true,
                term: "202509",
            },
        ],
        meetingsFaculty: [
            {
                category: "01",
                class: "net.hedtech.banner.student.schedule.SectionSessionDecorator",
                courseReferenceNumber: "10758",
                faculty: [],
                meetingTime: {
                    beginTime: "1300",
                    building: "233",
                    buildingDescription: "Engineering Building",
                    campus: "M",
                    campusDescription: "Main (Gordon Head)",
                    category: "01",
                    class: "net.hedtech.banner.general.overall.MeetingTimeDecorator",
                    courseReferenceNumber: "10758",
                    creditHourSession: 1.5,
                    endDate: "Dec 03, 2025",
                    endTime: "1420", // 80 minute class
                    friday: false,
                    hoursWeek: 3,
                    meetingScheduleType: "LEC",
                    meetingType: "CLAS",
                    meetingTypeDescription: "Every Week",
                    monday: true,
                    room: "B201",
                    saturday: false,
                    startDate: "Sep 03, 2025",
                    sunday: false,
                    term: "202509",
                    thursday: true,
                    tuesday: false,
                    wednesday: false,
                },
                term: "202509",
            },
        ],
        reservedSeatSummary: null,
        sectionAttributes: null,
        instructionalMethod: "F2F",
        instructionalMethodDescription: "Face to Face Instruction",
    },
    {
        id: 272660,
        term: "202509",
        termDesc: "First Term: Sep - Dec 2025",
        courseReferenceNumber: "10759",
        partOfTerm: "1",
        courseNumber: "115",

        subject: "CSC",
        subjectDescription: "Computer Science",
        sequenceNumber: "B02",
        campusDescription: "Main (Gordon Head)",
        scheduleTypeDescription: "Lab",
        courseTitle: "Fundamentals of Programming II",
        creditHours: 0,
        maximumEnrollment: 30,
        enrollment: 21,
        seatsAvailable: 9,
        waitCapacity: 0,
        waitCount: 0,
        waitAvailable: 0,
        crossList: null,
        crossListCapacity: null,
        crossListCount: null,
        crossListAvailable: null,
        creditHourHigh: 1.5,
        creditHourLow: 0,
        creditHourIndicator: "OR",
        openSection: true,
        linkIdentifier: "B1",
        isSectionLinked: true,
        subjectCourse: "CSC115",
        faculty: [
            {
                bannerId: "678901",
                category: "01",
                class: "net.hedtech.banner.student.faculty.FacultyDecorator",
                courseReferenceNumber: "10759",
                displayName: "TA: Alex Thompson",
                emailAddress: "athompson@uvic.ca",
                primaryIndicator: true,
                term: "202509",
            },
        ],
        meetingsFaculty: [
            {
                category: "01",
                class: "net.hedtech.banner.student.schedule.SectionSessionDecorator",
                courseReferenceNumber: "10759",
                faculty: [],
                meetingTime: {
                    beginTime: "1030",
                    building: "233",
                    buildingDescription: "Engineering Building",
                    campus: "M",
                    campusDescription: "Main (Gordon Head)",
                    category: "01",
                    class: "net.hedtech.banner.general.overall.MeetingTimeDecorator",
                    courseReferenceNumber: "10759",
                    creditHourSession: 0,
                    endDate: "Dec 03, 2025",
                    endTime: "1220", // 110 minute lab
                    friday: false,
                    hoursWeek: 2,
                    meetingScheduleType: "LAB",
                    meetingType: "CLAS",
                    meetingTypeDescription: "Every Week",
                    monday: false,
                    room: "Lab 105",
                    saturday: false,
                    startDate: "Sep 08, 2025",
                    sunday: false,
                    term: "202509",
                    thursday: false,
                    tuesday: true,
                    wednesday: false,
                },
                term: "202509",
            },
        ],
        reservedSeatSummary: null,
        sectionAttributes: null,
        instructionalMethod: "F2F",
        instructionalMethodDescription: "Face to Face Instruction",
    },
    {
        id: 273112,
        term: "202509",
        termDesc: "First Term: Sep - Dec 2025",
        courseReferenceNumber: "11211",
        partOfTerm: "1",
        courseNumber: "749",

        subject: "EDCI",
        subjectDescription: "Curriculum and Instruction",
        sequenceNumber: "A01",
        campusDescription: "Main (Gordon Head)",
        scheduleTypeDescription: "Lecture",
        courseTitle: "General Methods of Second Language Teaching",
        creditHours: 1.5,
        maximumEnrollment: 10,
        enrollment: 0,
        seatsAvailable: 10,
        waitCapacity: 0,
        waitCount: 0,
        waitAvailable: 0,
        crossList: null,
        crossListCapacity: null,
        crossListCount: null,
        crossListAvailable: null,
        creditHourHigh: null,
        creditHourLow: 1.5,
        creditHourIndicator: null,
        openSection: true,
        linkIdentifier: null,
        isSectionLinked: false,
        subjectCourse: "EDCI749",
        faculty: [
            {
                bannerId: "234567",
                category: "01",
                class: "net.hedtech.banner.student.faculty.FacultyDecorator",
                courseReferenceNumber: "11211",
                displayName: "Dr. Maria Santos",
                emailAddress: "msantos@uvic.ca",
                primaryIndicator: true,
                term: "202509",
            },
        ],
        meetingsFaculty: [
            {
                category: "01",
                class: "net.hedtech.banner.student.schedule.SectionSessionDecorator",
                courseReferenceNumber: "11211",
                faculty: [],
                meetingTime: {
                    beginTime: "0830",
                    building: "115",
                    buildingDescription: "Education Building",
                    campus: "M",
                    campusDescription: "Main (Gordon Head)",
                    category: "01",
                    class: "net.hedtech.banner.general.overall.MeetingTimeDecorator",
                    courseReferenceNumber: "11211",
                    creditHourSession: 1.5,
                    endDate: "Dec 03, 2025",
                    endTime: "1200", // Long 3.5 hour class
                    friday: false,
                    hoursWeek: 3,
                    meetingScheduleType: "LEC",
                    meetingType: "CLAS",
                    meetingTypeDescription: "Every Week",
                    monday: false,
                    room: "205",
                    saturday: false,
                    startDate: "Sep 03, 2025",
                    sunday: false,
                    term: "202509",
                    thursday: false,
                    tuesday: true,
                    wednesday: false,
                },
                term: "202509",
            },
        ],
        reservedSeatSummary: null,
        sectionAttributes: null,
        instructionalMethod: "F2F",
        instructionalMethodDescription: "Face to Face Instruction",
    },
    {
        id: 275663,
        term: "202509",
        termDesc: "First Term: Sep - Dec 2025",
        courseReferenceNumber: "13762",
        partOfTerm: "1Y",
        courseNumber: "336",

        subject: "MUS",
        subjectDescription: "Music",
        sequenceNumber: "A01",
        campusDescription: "Main (Gordon Head)",
        scheduleTypeDescription: "Lecture",
        courseTitle: "Strings Techniques and Mentoring",
        creditHours: 0.75,
        maximumEnrollment: 12,
        enrollment: 5,
        seatsAvailable: 7,
        waitCapacity: 100,
        waitCount: 0,
        waitAvailable: 100,
        crossList: null,
        crossListCapacity: null,
        crossListCount: null,
        crossListAvailable: null,
        creditHourHigh: 1.5,
        creditHourLow: 0,
        creditHourIndicator: "TO",
        openSection: true,
        linkIdentifier: null,
        isSectionLinked: false,
        subjectCourse: "MUS336",
        faculty: [
            {
                bannerId: "890123",
                category: "01",
                class: "net.hedtech.banner.student.faculty.FacultyDecorator",
                courseReferenceNumber: "13762",
                displayName: "Prof. Lisa Anderson",
                emailAddress: "landerson@uvic.ca",
                primaryIndicator: true,
                term: "202509",
            },
        ],
        meetingsFaculty: [
            {
                category: "01",
                class: "net.hedtech.banner.student.schedule.SectionSessionDecorator",
                courseReferenceNumber: "13762",
                faculty: [],
                meetingTime: {
                    beginTime: "1030",
                    building: "123",
                    buildingDescription: "Music Building",
                    campus: "M",
                    campusDescription: "Main (Gordon Head)",
                    category: "01",
                    class: "net.hedtech.banner.general.overall.MeetingTimeDecorator",
                    courseReferenceNumber: "13762",
                    creditHourSession: 0.75,
                    endDate: "Dec 03, 2025",
                    endTime: "1120", // 50 minute class
                    friday: false,
                    hoursWeek: 1,
                    meetingScheduleType: "LEC",
                    meetingType: "CLAS",
                    meetingTypeDescription: "Every Week",
                    monday: false,
                    room: "Studio A",
                    saturday: false,
                    startDate: "Sep 03, 2025",
                    sunday: false,
                    term: "202509",
                    thursday: true,
                    tuesday: false,
                    wednesday: false,
                },
                term: "202509",
            },
        ],
        reservedSeatSummary: null,
        sectionAttributes: null,
        instructionalMethod: "F2F",
        instructionalMethodDescription: "Face to Face Instruction",
    },
    {
        id: 274486,
        term: "202509",
        termDesc: "First Term: Sep - Dec 2025",
        courseReferenceNumber: "12585",
        partOfTerm: "1",
        courseNumber: "360",

        subject: "NURS",
        subjectDescription: "Nursing",
        sequenceNumber: "A30",
        campusDescription: "Selkirk College, BC",
        scheduleTypeDescription: "Lecture",
        courseTitle: "Professional Practice VI: Nursing Research",
        creditHours: 1.5,
        maximumEnrollment: 35,
        enrollment: 27,
        seatsAvailable: 8,
        waitCapacity: 0,
        waitCount: 0,
        waitAvailable: 0,
        crossList: null,
        crossListCapacity: null,
        crossListCount: null,
        crossListAvailable: null,
        creditHourHigh: null,
        creditHourLow: 1.5,
        creditHourIndicator: null,
        openSection: true,
        linkIdentifier: null,
        isSectionLinked: false,
        subjectCourse: "NURS360",
        faculty: [
            {
                bannerId: "901234",
                category: "01",
                class: "net.hedtech.banner.student.faculty.FacultyDecorator",
                courseReferenceNumber: "12585",
                displayName: "Dr. Patricia Lee",
                emailAddress: "plee@uvic.ca",
                primaryIndicator: true,
                term: "202509",
            },
        ],
        meetingsFaculty: [
            {
                category: "01",
                class: "net.hedtech.banner.student.schedule.SectionSessionDecorator",
                courseReferenceNumber: "12585",
                faculty: [],
                meetingTime: {
                    beginTime: null,
                    building: null,
                    buildingDescription: null,
                    campus: null,
                    campusDescription: null,
                    category: "01",
                    class: "net.hedtech.banner.general.overall.MeetingTimeDecorator",
                    courseReferenceNumber: "12585",
                    creditHourSession: 1.5,
                    endDate: "Dec 03, 2025",
                    endTime: null,
                    friday: false,
                    hoursWeek: 0,
                    meetingScheduleType: "LEC",
                    meetingType: "CLAS",
                    meetingTypeDescription: "Every Week",
                    monday: false,
                    room: null,
                    saturday: false,
                    startDate: "Sep 03, 2025",
                    sunday: false,
                    term: "202509",
                    thursday: false,
                    tuesday: false,
                    wednesday: false,
                },
                term: "202509",
            },
        ],
        reservedSeatSummary: null,
        sectionAttributes: null,
        instructionalMethod: "F2F",
        instructionalMethodDescription: "Face to Face Instruction",
    },
    {
        id: 280001,
        term: "202509",
        termDesc: "First Term: Sep - Dec 2025",
        courseReferenceNumber: "15001",
        partOfTerm: "1",
        courseNumber: "201",

        subject: "MATH",
        subjectDescription: "Mathematics",
        sequenceNumber: "A01",
        campusDescription: "Main (Gordon Head)",
        scheduleTypeDescription: "Lecture",
        courseTitle: "Calculus II",
        creditHours: 1.5,
        maximumEnrollment: 80,
        enrollment: 75,
        seatsAvailable: 5,
        waitCapacity: 20,
        waitCount: 15,
        waitAvailable: 5,
        crossList: null,
        crossListCapacity: null,
        crossListCount: null,
        crossListAvailable: null,
        creditHourHigh: null,
        creditHourLow: 1.5,
        creditHourIndicator: null,
        openSection: true,
        linkIdentifier: null,
        isSectionLinked: false,
        subjectCourse: "MATH201",
        faculty: [
            {
                bannerId: "012345",
                category: "01",
                class: "net.hedtech.banner.student.faculty.FacultyDecorator",
                courseReferenceNumber: "15001",
                displayName: "Prof. Robert Wilson",
                emailAddress: "rwilson@uvic.ca",
                primaryIndicator: true,
                term: "202509",
            },
        ],
        meetingsFaculty: [
            {
                category: "01",
                class: "net.hedtech.banner.student.schedule.SectionSessionDecorator",
                courseReferenceNumber: "15001",
                faculty: [],
                meetingTime: {
                    beginTime: "0900",
                    building: "161",
                    buildingDescription: "Science Building",
                    campus: "M",
                    campusDescription: "Main (Gordon Head)",
                    category: "01",
                    class: "net.hedtech.banner.general.overall.MeetingTimeDecorator",
                    courseReferenceNumber: "15001",
                    creditHourSession: 1.5,
                    endDate: "Dec 03, 2025",
                    endTime: "1030", // 90 minute class
                    friday: false,
                    hoursWeek: 3,
                    meetingScheduleType: "LEC",
                    meetingType: "CLAS",
                    meetingTypeDescription: "Every Week",
                    monday: true,
                    room: "A201",
                    saturday: false,
                    startDate: "Sep 03, 2025",
                    sunday: false,
                    term: "202509",
                    thursday: false,
                    tuesday: false,
                    wednesday: true,
                },
                term: "202509",
            },
        ],
        reservedSeatSummary: null,
        sectionAttributes: null,
        instructionalMethod: "F2F",
        instructionalMethodDescription: "Face to Face Instruction",
    },
    {
        id: 280002,
        term: "202509",
        termDesc: "First Term: Sep - Dec 2025",
        courseReferenceNumber: "15002",
        partOfTerm: "1",
        courseNumber: "201",

        subject: "MATH",
        sequenceNumber: "T01",
        campusDescription: "Main (Gordon Head)",
        scheduleTypeDescription: "Tutorial",
        courseTitle: "Calculus II",
        creditHours: 0,
        maximumEnrollment: 25,
        enrollment: 20,
        seatsAvailable: 5,
        waitCapacity: 0,
        waitCount: 0,
        waitAvailable: 0,
        crossList: null,
        crossListCapacity: null,
        crossListCount: null,
        crossListAvailable: null,
        creditHourHigh: null,
        creditHourLow: 0,
        creditHourIndicator: null,
        openSection: true,
        linkIdentifier: "T1",
        isSectionLinked: true,
        subjectCourse: "MATH201",
        faculty: [
            {
                bannerId: "123450",
                category: "01",
                class: "net.hedtech.banner.student.faculty.FacultyDecorator",
                courseReferenceNumber: "15002",
                displayName: "TA: Sarah Kim",
                emailAddress: "skim@uvic.ca",
                primaryIndicator: true,
                term: "202509",
            },
        ],
        meetingsFaculty: [
            {
                category: "01",
                class: "net.hedtech.banner.student.schedule.SectionSessionDecorator",
                courseReferenceNumber: "15002",
                faculty: [],
                meetingTime: {
                    beginTime: "1100",
                    building: "161",
                    buildingDescription: "Science Building",
                    campus: "M",
                    campusDescription: "Main (Gordon Head)",
                    category: "01",
                    class: "net.hedtech.banner.general.overall.MeetingTimeDecorator",
                    courseReferenceNumber: "15002",
                    creditHourSession: 0,
                    endDate: "Dec 03, 2025",
                    endTime: "1150", // 50 minute tutorial
                    friday: false,
                    hoursWeek: 1,
                    meetingScheduleType: "TUT",
                    meetingType: "CLAS",
                    meetingTypeDescription: "Every Week",
                    monday: false,
                    room: "B105",
                    saturday: false,
                    startDate: "Sep 03, 2025",
                    sunday: false,
                    term: "202509",
                    thursday: false,
                    tuesday: false,
                    wednesday: false,
                },
                term: "202509",
            },
        ],
        reservedSeatSummary: null,
        sectionAttributes: null,
        instructionalMethod: "F2F",
        instructionalMethodDescription: "Face to Face Instruction",
    },
    {
        id: 280010,
        term: "202509",
        termDesc: "First Term: Sep - Dec 2025",
        courseReferenceNumber: "15010",
        partOfTerm: "1",
        courseNumber: "200",

        subject: "PSYC",
        subjectDescription: "Psychology",
        sequenceNumber: "A01",
        campusDescription: "Main (Gordon Head)",
        scheduleTypeDescription: "Lecture",
        courseTitle: "Research Methods in Psychology",
        creditHours: 1.5,
        maximumEnrollment: 200,
        enrollment: 180,
        seatsAvailable: 20,
        waitCapacity: 50,
        waitCount: 10,
        waitAvailable: 40,
        crossList: null,
        crossListCapacity: null,
        crossListCount: null,
        crossListAvailable: null,
        creditHourHigh: null,
        creditHourLow: 1.5,
        creditHourIndicator: null,
        openSection: true,
        linkIdentifier: null,
        isSectionLinked: false,
        subjectCourse: "PSYC200",
        faculty: [
            {
                bannerId: "345678",
                category: "01",
                class: "net.hedtech.banner.student.faculty.FacultyDecorator",
                courseReferenceNumber: "15010",
                displayName: "Dr. Emily Rodriguez",
                emailAddress: "erodriguez@uvic.ca",
                primaryIndicator: true,
                term: "202509",
            },
        ],
        meetingsFaculty: [
            {
                category: "01",
                class: "net.hedtech.banner.student.schedule.SectionSessionDecorator",
                courseReferenceNumber: "15010",
                faculty: [],
                meetingTime: {
                    beginTime: "1000",
                    building: "161",
                    buildingDescription: "Science Building",
                    campus: "M",
                    campusDescription: "Main (Gordon Head)",
                    category: "01",
                    class: "net.hedtech.banner.general.overall.MeetingTimeDecorator",
                    courseReferenceNumber: "15010",
                    creditHourSession: 1.5,
                    endDate: "Dec 03, 2025",
                    endTime: "1120", // 80 minute class
                    friday: false,
                    hoursWeek: 2.5,
                    meetingScheduleType: "LEC",
                    meetingType: "CLAS",
                    meetingTypeDescription: "Every Week",
                    monday: false,
                    room: "C150",
                    saturday: false,
                    startDate: "Sep 03, 2025",
                    sunday: false,
                    term: "202509",
                    thursday: false,
                    tuesday: true,
                    wednesday: false,
                },
                term: "202509",
            },
        ],
        reservedSeatSummary: null,
        sectionAttributes: null,
        instructionalMethod: "HYB",
        instructionalMethodDescription: "Hybrid Instruction",
    },
    {
        id: 280011,
        term: "202509",
        termDesc: "First Term: Sep - Dec 2025",
        courseReferenceNumber: "15011",
        partOfTerm: "1",
        courseNumber: "250",

        subject: "ECON",
        subjectDescription: "Economics",
        sequenceNumber: "A01",
        campusDescription: "Main (Gordon Head)",
        scheduleTypeDescription: "Lecture",
        courseTitle: "Intermediate Microeconomics",
        creditHours: 1.5,
        maximumEnrollment: 100,
        enrollment: 85,
        seatsAvailable: 15,
        waitCapacity: 25,
        waitCount: 8,
        waitAvailable: 17,
        crossList: null,
        crossListCapacity: null,
        crossListCount: null,
        crossListAvailable: null,
        creditHourHigh: null,
        creditHourLow: 1.5,
        creditHourIndicator: null,
        openSection: true,
        linkIdentifier: null,
        isSectionLinked: false,
        subjectCourse: "ECON250",
        faculty: [
            {
                bannerId: "456789",
                category: "01",
                class: "net.hedtech.banner.student.faculty.FacultyDecorator",
                courseReferenceNumber: "15011",
                displayName: "Prof. David Kim",
                emailAddress: "dkim@uvic.ca",
                primaryIndicator: true,
                term: "202509",
            },
        ],
        meetingsFaculty: [
            {
                category: "01",
                class: "net.hedtech.banner.student.schedule.SectionSessionDecorator",
                courseReferenceNumber: "15011",
                faculty: [],
                meetingTime: {
                    beginTime: "1030",
                    building: "233",
                    buildingDescription: "Engineering Building",
                    campus: "M",
                    campusDescription: "Main (Gordon Head)",
                    category: "01",
                    class: "net.hedtech.banner.general.overall.MeetingTimeDecorator",
                    courseReferenceNumber: "15011",
                    creditHourSession: 1.0,
                    endDate: "Oct 15, 2025",
                    endTime: "1120", // 50 minute class - CONFLICTS with PSYC200
                    friday: false,
                    hoursWeek: 2,
                    meetingScheduleType: "LEC",
                    meetingType: "CLAS",
                    meetingTypeDescription: "First Half Term",
                    monday: false,
                    room: "A305",
                    saturday: false,
                    startDate: "Sep 03, 2025",
                    sunday: false,
                    term: "202509",
                    thursday: false,
                    tuesday: true,
                    wednesday: false,
                },
                term: "202509",
            },
            {
                category: "02",
                class: "net.hedtech.banner.student.schedule.SectionSessionDecorator",
                courseReferenceNumber: "15011",
                faculty: [],
                meetingTime: {
                    beginTime: "1700",
                    building: "233",
                    buildingDescription: "Engineering Building",
                    campus: "M",
                    campusDescription: "Main (Gordon Head)",
                    category: "02",
                    class: "net.hedtech.banner.general.overall.MeetingTimeDecorator",
                    courseReferenceNumber: "15011",
                    creditHourSession: 0.5,
                    endDate: "Dec 03, 2025",
                    endTime: "1750", // 50 minute class
                    friday: true,
                    hoursWeek: 1,
                    meetingScheduleType: "LEC",
                    meetingType: "CLAS",
                    meetingTypeDescription: "Second Half Term",
                    monday: false,
                    room: "A305",
                    saturday: false,
                    startDate: "Oct 16, 2025",
                    sunday: false,
                    term: "202509",
                    thursday: false,
                    tuesday: false,
                    wednesday: false,
                },
                term: "202509",
            },
        ],
        reservedSeatSummary: null,
        sectionAttributes: null,
        instructionalMethod: "F2F",
        instructionalMethodDescription: "Face to Face Instruction",
    },
    {
        id: 280012,
        term: "202509",
        termDesc: "First Term: Sep - Dec 2025",
        courseReferenceNumber: "15012",
        partOfTerm: "1",
        courseNumber: "101",

        subject: "PHIL",
        subjectDescription: "Philosophy",
        sequenceNumber: "A01",
        campusDescription: "Online",
        scheduleTypeDescription: "Lecture",
        courseTitle: "Introduction to Philosophy",
        creditHours: 1.5,
        maximumEnrollment: 300,
        enrollment: 250,
        seatsAvailable: 50,
        waitCapacity: 0,
        waitCount: 0,
        waitAvailable: 0,
        crossList: null,
        crossListCapacity: null,
        crossListCount: null,
        crossListAvailable: null,
        creditHourHigh: null,
        creditHourLow: 1.5,
        creditHourIndicator: null,
        openSection: true,
        linkIdentifier: null,
        isSectionLinked: false,
        subjectCourse: "PHIL101",
        faculty: [
            {
                bannerId: "567890",
                category: "01",
                class: "net.hedtech.banner.student.faculty.FacultyDecorator",
                courseReferenceNumber: "15012",
                displayName: "Dr. Jennifer Walsh",
                emailAddress: "jwalsh@uvic.ca",
                primaryIndicator: true,
                term: "202509",
            },
        ],
        meetingsFaculty: [
            {
                category: "01",
                class: "net.hedtech.banner.student.schedule.SectionSessionDecorator",
                courseReferenceNumber: "15012",
                faculty: [],
                meetingTime: {
                    beginTime: null,
                    building: null,
                    buildingDescription: null,
                    campus: null,
                    campusDescription: null,
                    category: "01",
                    class: "net.hedtech.banner.general.overall.MeetingTimeDecorator",
                    courseReferenceNumber: "15012",
                    creditHourSession: 1.5,
                    endDate: "Dec 03, 2025",
                    endTime: null,
                    friday: false,
                    hoursWeek: 0,
                    meetingScheduleType: "LEC",
                    meetingType: "CLAS",
                    meetingTypeDescription: "Asynchronous Online",
                    monday: false,
                    room: null,
                    saturday: false,
                    startDate: "Sep 03, 2025",
                    sunday: false,
                    term: "202509",
                    thursday: false,
                    tuesday: false,
                    wednesday: false,
                },
                term: "202509",
            },
        ],
        reservedSeatSummary: null,
        sectionAttributes: null,
        instructionalMethod: "ONL",
        instructionalMethodDescription: "Online Instruction",
    },
];
